# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0002_auto_20170908_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empDepartment',
            field=models.CharField(choices=[('iwd', 'IWD'), ('et', 'Establishment'), ('library', 'Library'), ('pc', 'Placement Cell'), ('acad', 'Academics'), ('ns', 'Natural Science'), ('cse', 'CSE'), ('ece', 'ECE'), ('me', 'ME'), ('otd', 'Office of Dean'), ('fna', 'Finance and Accounts'), ('directorate', 'Directorate')], max_length=36),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empDesignation',
            field=models.CharField(choices=[('driver', 'Driver'), ('ja', 'Junior Assistant'), ('sa', 'Senior Assistant'), ('jt', 'Junior Technician'), ('st', 'Senior Technician'), ('ar', 'Assistant Registrar'), ('dr', 'Deputy Registrar'), ('rr', 'Registrar'), ('Research Engineer', 'Research Engineer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=36),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empPassword',
            field=models.CharField(default='pass', max_length=36),
        ),
        migrations.AlterField(
            model_name='employeeleaveauthority',
            name='authDesignation',
            field=models.CharField(choices=[('rr', 'Registrar'), ('director', 'Director'), ('ccc', 'Coordinator Computer Center'), ('wi', 'Workshop In-charge'), ('headns', 'HOD NS'), ('hodcse', 'HOD CSE'), ('hodece', 'HOD ECE'), ('hodme', 'HOD ME'), ('deanacad', 'Dean Academics'), ('deanstudents', 'Dean Students'), ('deanRSPC', 'Dean RSPC')], max_length=18),
        ),
    ]
